import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
  background: {
    flex: 1,
    backgroundColor: "#2F2F2F",
  },
  boxInput: {
    width: "90%",
    borderRadius: 15,
    marginTop: 10,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  textInput: {
    marginHorizontal: 15,
    backgroundColor: "#2f2f2f",
    fontSize: 16,
    lineHeight: 18,
    letterSpacing: 0.16,
    paddingHorizontal: 20,
    paddingVertical: 10,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    maxWidth: "100%",
    borderRadius: 15,
    borderWidth: 2,
    borderColor: "#52B6CE",
    gap: 10,
    marginBottom: 20,
    marginTop: 20,
  },
  filterBtn: {
    backgroundColor: "#fff",
    borderRadius: 15,
    padding: 10,
    marginBottom: 8,
  },
  textInputTyping: {
    flex: 1,
    lineHeight: 18.4,
    letterSpacing: 0.16,
    fontSize: 16,
    color: "#fff",
  },
  boxSearch: {
    display: "flex",
    width: "100%",
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
    paddingHorizontal: 20,
    paddingVertical: 10,
  },
  leftBoxSearch: {
    flex: 1,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    gap: 15,
  },
  textBoxSearch: {
    alignSelf: "center",
    fontSize: 16,
    color: "#898989",
  },
});

export default styles;
