import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  headerCard: {
    width: "100%",
    height: 250,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#1F1F1F",
    borderBottomRightRadius: 50,
    paddingVertical: 10,
    marginBottom: 20,
  },
  titleMessage: {
    maxWidth: "70%",
    marginTop: 20,
    alignSelf: "flex-start",
    paddingHorizontal: 20,
    color: "#fff",
    fontSize: 33,
    lineHeight: 37,
    letterSpacing: 0.33,
  },
  boxInput: {
    flex: 1,
    width: "90%",
    borderRadius: 15,
    marginTop: 10,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  textInput: {
    flex: 1,
    backgroundColor: "#fff",
    fontSize: 16,
    lineHeight: 18,
    letterSpacing: 0.16,
    paddingHorizontal: 20,
    paddingVertical: 10,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    maxWidth: "100%",
    borderRadius: 15,
    marginBottom: 10,
    gap: 10,
  },
  filterBtn: {
    backgroundColor: "#fff",
    borderRadius: 15,
    padding: 10,
    marginBottom: 8,
  },
});

export default styles;
