export const sexoArr = [
  { label: "Masculino", value: "M" },
  { label: "Feminino", value: "F" },
];
export const meses = [
  { label: "Janeiro", value: "JAN" },
  { label: "Fevereiro", value: "FEV" },
  { label: "Março", value: "MAR" },
  { label: "Abril", value: "ABR" },
  { label: "Maio", value: "MAI" },
  { label: "Junho", value: "JUN" },
  { label: "Julho", value: "JUL" },
  { label: "Agosto", value: "AGO" },
  { label: "Setembro", value: "SET" },
  { label: "Outubro", value: "OUT" },
  { label: "Novembro", value: "NOV" },
  { label: "Dezembro", value: "DEZ" },
];
export const estadosBrasil = [
  { label: "Acre", value: "AC" },
  { label: "Alagoas", value: "AL" },
  { label: "Amapá", value: "AP" },
  { label: "Amazonas", value: "AM" },
  { label: "Bahia", value: "BA" },
  { label: "Ceará", value: "CE" },
  { label: "Distrito Federal", value: "DF" },
  { label: "Espírito Santo", value: "ES" },
  { label: "Goiás", value: "GO" },
  { label: "Maranhão", value: "MA" },
  { label: "Mato Grosso", value: "MT" },
  { label: "Mato Grosso do Sul", value: "MS" },
  { label: "Minas Gerais", value: "MG" },
  { label: "Pará", value: "PA" },
  { label: "Paraíba", value: "PB" },
  { label: "Paraná", value: "PR" },
  { label: "Pernambuco", value: "PE" },
  { label: "Piauí", value: "PI" },
  { label: "Rio de Janeiro", value: "RJ" },
  { label: "Rio Grande do Norte", value: "RN" },
  { label: "Rio Grande do Sul", value: "RS" },
  { label: "Rondônia", value: "RO" },
  { label: "Roraima", value: "RR" },
  { label: "Santa Catarina", value: "SC" },
  { label: "São Paulo", value: "SP" },
  { label: "Sergipe", value: "SE" },
  { label: "Tocantins", value: "TO" },
];
export const capitaisBrasil = [
  { label: "Rio Branco", value: "AC" },
  { label: "Maceió", value: "AL" },
  { label: "Macapá", value: "AP" },
  { label: "Manaus", value: "AM" },
  { label: "Salvador", value: "BA" },
  { label: "Fortaleza", value: "CE" },
  { label: "Brasília", value: "DF" },
  { label: "Vitória", value: "ES" },
  { label: "Goiânia", value: "GO" },
  { label: "São Luís", value: "MA" },
  { label: "Cuiabá", value: "MT" },
  { label: "Campo Grande", value: "MS" },
  { label: "Belo Horizonte", value: "MG" },
  { label: "Belém", value: "PA" },
  { label: "João Pessoa", value: "PB" },
  { label: "Curitiba", value: "PR" },
  { label: "Recife", value: "PE" },
  { label: "Teresina", value: "PI" },
  { label: "Rio de Janeiro", value: "RJ" },
  { label: "Natal", value: "RN" },
  { label: "Porto Alegre", value: "RS" },
  { label: "Porto Velho", value: "RO" },
  { label: "Boa Vista", value: "RR" },
  { label: "Florianópolis", value: "SC" },
  { label: "São Paulo", value: "SP" },
  { label: "Aracaju", value: "SE" },
  { label: "Palmas", value: "TO" },
];
